import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../components/ReduxProvider/ReduxProvider";
import { Toaster } from "react-hot-toast";
import { AudioProvider } from "../components/AudioContext/AudioContext";
import { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Skypro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReduxProvider>
          <AudioProvider>
            <SkeletonTheme baseColor="#313131" highlightColor="#525252" duration={3.5}>
              <div className="wrapper">
                <div className="container">{children}</div>
              </div>
            </SkeletonTheme>
            <Toaster position="bottom-center" reverseOrder={false} />
          </AudioProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
