import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ReduxProvider from '../components/ReduxProvider/ReduxProvider';
import { Toaster } from 'react-hot-toast';
import { AudioProvider } from '../components/AudioContext/AudioContext';

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Skypro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReduxProvider>
          <AudioProvider>
            <div className="wrapper">
              <div className="container">{children}</div>
            </div>
            <Toaster position="bottom-center" reverseOrder={false} />
          </AudioProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
